config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins
  get 'comments/new'

  resources :posts do
    resources :comments
    resources :charges
    resources :likes do
    	collection do
    		delete :destroy
    	end
    end
  end

  root 'posts#index'

  resources :tags
  resources :orders

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :posts
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  def number
  	date_section = created_at.strftime('%d%m%y')
  	id_section =  "%04d" % id

  	date_section + id_section
  end


end

app/models/post.rb
class Post < ActiveRecord::Base

 	has_attached_file :picture, 
 	styles: { medium: '300x300>' },
 	storage: :s3,
 	s3_credentials: {
 		bucket: 'flimstagram',
 		access_key_id: Rails.application.secrets.s3_access_key,
 		secret_access_key: Rails.application.secrets.s3_secret_key
 	}
 	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
 	has_many :comments	
 	has_many :likes
 	belongs_to :user
 	has_and_belongs_to_many :tags


 	def tag_names
 		''
 	end

 	def tag_names=(tag_names)
 		return if tag_names.blank?
 		
 		tag_names.split(/,\s?/).uniq.each do |tag_name|
 			hash_name = '#' + tag_name.delete('#')

			unique_tag = Tag.find_or_create_by(name: hash_name)
			self.tags << unique_tag
		end
 	end
end

app/models/tag.rb
class Tag < ActiveRecord::Base

	has_and_belongs_to_many :posts
	validates :name, uniqueness: true

	def to_param 
		name.delete('#')
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	before_action :authenticate_user!

	def new
		@post = Post.find params[:post_id]
	end

	def create

		@post = Post.find params[:post_id]
	  
	  # Amount in cents
	  @amount = 30000

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => "Print of #{@post.description}",
	    :currency    => 'gbp'
	  )

	  Order.create(user: current_user, post: @post)
	  flash[:notice] = "Thanks for your order"
	  redirect_to "/posts"

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to post_charges_path(@post)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  	@post = Post.find(params[:post_id])
  	@comment = Comment.new
  end

  def create
  	@post = Post.find(params[:post_id])
  	@post.comments.create!(params[:comment].permit(:comment))
		redirect_to '/posts'
  end

end

app/controllers/likes_controller.rb
 class LikesController < ApplicationController
	before_action :authenticate_user!

	def create
		@post = Post.find params[:post_id]
		@post.likes.create(user: current_user)
		WebsocketRails[:likes].trigger 'new', { id: @post.id, new_like_count: @post.likes.count }
		render nothing: true
	end

	def destroy 
		@post = Post.find(params[:post_id])
		@like = @post.likes.find_by(user_id: current_user.id)
		@like.destroy
		WebsocketRails[:likes].trigger 'destroy', { id: @post.id, new_like_count: @post.likes.count }
		render nothing: true
		# redirect_to '/posts'
	end



end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
		authenticate_admin!
		@orders = Order.all
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except:[:index]

	def index
		@all_posts = Post.all
		@post = Post.new
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params['post'].permit(:picture, :description, :tag_names))
		@post.user = current_user
		if @post.save!
			flash[:notice] = 'Post uploaded successfully!'
			redirect_to '/posts'
		else
			flash[:notice] = 'Error: file is not valid!'
			render 'index'
		end
	end

	def destroy
		
		# @post = current_user.posts.find(params[:id]) is used in place of:
		# "@post = Post.find(params[:id])
		# if @post.user == current_user
		# else" because it does not retrieve the record from the database and is more robust.
		# This would become increasingly important in complex actions where we want to prevent
		# the record being retrieved at all.
		@post = current_user.posts.find(params[:id])
		@post.delete
		flash[:notice] = 'Deleted successfully!'
	rescue ActiveRecord::RecordNotFound
		flash[:alert] = 'This is not your post!'
	ensure 
		redirect_to '/posts'
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def show 
		@tag = Tag.find_by(name: '#' + params[:id])
	end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/charges/new.html.erb
<div class='container'>
	<%= form_tag post_charges_path(@post) do %>
		
		<h1>Buy a print for £300</h1>

	  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	          data-key="<%= Rails.application.secrets.stripe_public_key %>"
	          data-description="A lovely snap"
	          data-amount="30000"></script>
	<% end %>
</div>

app/views/comments/new.html.erb
<br>
<br>
	<%= form_for [@post, @comment] do |f| %>

		<%= f.label :comment %>
		<%= f.text_area :comment %>
		<%= f.submit "Add comment" %>

	<% end %>

app/views/orders/index.html.erb
<div class='orders'>
	<% if @orders.any? %>
		<% @orders.each  do |order| %>
			<%= order.user.email %>
			<%= link_to order.post.description, '/posts' %>
			<%= order.number %>
		<% end %>
	<% else %>

	No orders have been placed

	<% end %>
</div>

app/views/posts/_post.html.erb
<div class= 'col-md-4 post' data-id='<%= post.id %>' >
	<h2><%= post.description %></h2>
	<% if post.user %>
		<p>Posted by: <%= post.user.email %></p>
	<% end %>
	<% if post.picture.exists? %>
		<%= image_tag post.picture.url(:medium), class: 'uploaded-pic' %>
	<% end %>
	<br/><br/>
	<% post.tags.each do |tag| %>
			<%= link_to tag.name, tag_path(tag) %>
	<% end %>

	<ul>
		<% post.comments.each do |comment| %>
			<li><%= comment.comment %> </li>
		<% end %>
	</ul>

	<% if user_signed_in? %>
		<%= link_to "Add comment", new_post_comment_path(post), class: 'btn btn-primary btn-lg' %>
	<% end %>

	<% if post.user == current_user %>
		<%= link_to "Delete post", post_path(post), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary btn-lg' %>
	<% end %>

	<% if user_signed_in? %>
		<% if like = current_user.likes.find_by(post: post) %>
		  <%= link_to "♥ #{post.likes.count}", post_like_path(post.id, like), :class => 'btn btn-lg btn-default btn-unlike'%>	     
		<% else %>
		  <%= link_to "♥ #{post.likes.count}", post_likes_path(post), :class => 'btn btn-lg btn-default btn-like'%>
		<% end %>
	<% else %>
  	<%= link_to "♥ #{post.likes.count}", new_user_session_path, :class => 'btn btn-lg btn-default btn-signin-like'%>
  <% end %>

   <%= link_to "Buy", new_post_charge_path(post), :class => 'btn btn-lg btn-default'%>


</div>

app/views/posts/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>flimstagram</h1>
    <p>The new home for your photos that no one wants to see</p>
    <p> 
    	<% if user_signed_in? %>
    	    <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: 'btn btn-primary btn-lg') %>
    	<% else %>	
    		<%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
    <% end %>
  </div>
</div>

<%= link_to 'Add new post', new_post_path, class: 'btn btn-primary btn-lg'%>

<div class= 'container'>
	<% if @all_posts.none? %>
		<Br/><br/>
			No posts have been made
			0 comments
		<Br/><br/>
	<% else %>
		<div class= 'row'>
			<%= render @all_posts %>
		</div>
	<% end %>
</div>

app/views/posts/new.html.erb
<br>
<br>

<%= form_for @post, html: { multipart: true } do |f| %>
	
	<%= f.label :picture %>
	<%= f.file_field :picture %>

	<%= f.label :description %> 
	<%= f.text_area :description %>

	<%= f.label :tag_names, 'Tags' %>
	<%= f.text_field :tag_names %>
	
	<%= f.button "Upload", action: "create" %>

<% end %>

app/views/tags/show.html.erb
<h1>All posts tagged with <%= @tag.name %></h1>

<div class='container'>
	<%= render @tag.posts%>
</div>